### ISSUE TITLE
Fullscreen exit doesn't reset widget height properly when exited with Escape key

### ISSUE THREAD

**Issue by gaardhus** [medialab/ipysigma#130]
## Issue
When exiting fullscreen with the escape key rather than the button, the height of divs are not reset properly. This results in a disappearing widget since height remains at 100%, but no parent container has a specified height.

## Fix
My TypeScript is not good enough, but I guess it's possible to add a key or eventlistener to deal with it.

**Comment by Yomguithereal** [comment]
Thanks @gaardhus. v0.20.1 is now live with a fix.
