### ISSUE TITLE
Add function to add node icons in different colours.

### ISSUE THREAD

**Issue by asgerkromand** [medialab/ipysigma#132]
I have seen in this [sandbox](https://codesandbox.io/s/pfzs3) that it's possible in javacript to add image, colour and border to a node. Is it possible to add this to the python package as well? The code from the sandbox is also put in below.

```
import Graph from "graphology";
import Sigma from "sigma";

import getNodeProgramImage from "sigma/rendering/webgl/programs/node.image";
import NodeProgramBorder from "./node.border";

import ForceSupervisor from "graphology-layout-force/worker";

const container = document.getElementById("sigma-container") as HTMLElement;

const graph = new Graph();

const RED = "#FA4F40";
const BLUE = "#727EE0";
const GREEN = "#5DB346";

graph.addNode("John", { size: 15, label: "John", type: "image", image: "./user.svg", color: RED });
graph.addNode("Mary", { size: 15, label: "Mary", type: "image", image: "./user.svg", color: RED });
graph.addNode("Suzan", { size: 15, label: "Suzan", type: "image", image: "./user.svg", color: RED });
graph.addNode("Nantes", { size: 15, label: "Nantes", type: "image", image: "./city.svg", color: BLUE });
graph.addNode("New-York", { size: 15, label: "New-York", type: "image", image: "./city.svg", color: BLUE });
graph.addNode("Sushis", { size: 7, label: "Sushis", type: "border", color: GREEN });
graph.addNode("Falafels", { size: 7, label: "Falafels", type: "border", color: GREEN });
graph.addNode("Kouign Amann", { size: 7, label: "Kouign Amann", type: "border", color: GREEN });
```

The reason is that I would very much like to make a two-mode network, where the two node types (persons and companies) have a different (base-)icon. Next I would need also to colour the nodes by a secondary node-partition. 

Hope this could be added.

**Comment by Yomguithereal** [comment]
Hello @asgerkromand, sure this could be added, but I am not sure how to link between local resources such as images you might have on disk next to your notebook and the widget's javascript context. What I wanted to do was maybe to select a well-know open source pictogram library instead and make people reference them by name for their nodes. What do you think?

**Comment by asgerkromand** [comment]
I pictogram library would do a great deal of the trick. I’m of the impression that people generally use pretty generic nodetypes (at least it social sciences, where I am placed), and it could be nice to have a selection for the most common cases.

Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Guillaume Plique ***@***.***>
Sendt: Monday, November 7, 2022 5:37:30 PM
Til: medialab/ipysigma ***@***.***>
Cc: Asger ***@***.***>; Mention ***@***.***>
Emne: Re: [medialab/ipysigma] Add function to add node icons in different colours. (Issue #132)


You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>


Hello @asgerkromand<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fasgerkromand&data=05%7C01%7Ccrm406%40sodas.ku.dk%7C535b70a718914f5ad2cf08dac0de5de2%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C638034358541703125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=frABKg2GfBwIzbcPLP4F%2Bgyao7FWyErBB7PrgHtNVWo%3D&reserved=0>, sure this could be added, but I am not sure how to link between local resources such as images you might have on disk next to your notebook and the widget's javascript context. What I wanted to do was maybe to select a well-know open source pictogram library instead and make people reference them by name for their nodes. What do you think?

**Comment by gaardhus** [comment]
I think the idea of having predefined icons is great, however perhaps together with the possibility of specifying your own source, or maybe even raw SVG paths like so?

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
  <g>
	  <g>
		  <path d="M482.159,136.181c-19.646-37.242-48.721-69.485-84.104-93.256C355.988,14.844,306.866,0,256,0    s-99.988,14.844-142.075,42.938c-35.362,23.758-64.437,56-84.067,93.211C10.324,172.759,0,214.203,0,256    c0,41.797,10.324,83.241,29.84,119.818c19.146,36.303,47.113,67.688,81.006,91.046v0.27h0.394    c1.045,0.717,2.076,1.452,3.132,2.154C156.285,497.23,205.259,512,256,512s99.715-14.77,141.619-42.706    c1.059-0.704,2.094-1.441,3.142-2.16h0.394v-0.27c33.896-23.363,61.861-54.746,80.988-91.014C501.676,339.241,512,297.796,512,256    C512,214.204,501.676,172.759,482.159,136.181z M110.845,447.356c-24.211-18.397-44.777-41.32-60.425-67.315h60.425V447.356z     M110.845,364.206H41.673c-15.943-31.32-24.586-64.994-25.706-100.289h94.878V364.206z M110.845,248.082H15.967    c1.12-35.284,9.759-68.951,25.707-100.289h69.172V248.082z M110.845,131.959H50.422c15.599-25.891,36.175-48.83,60.423-67.336    V131.959z M248.082,496.03c-43.356-1.403-85.088-14.318-121.402-37.615v-78.374h121.402V496.03z M248.082,364.206H126.68V263.918    h121.402V364.206z M248.082,248.082H126.68V147.794h121.402V248.082z M248.082,131.959H126.68V53.521    c36.357-23.255,78.082-36.149,121.402-37.551V131.959z M385.32,458.416c-36.308,23.293-78.042,36.211-121.402,37.614V380.041    H385.32V458.416z M385.32,364.206H263.918V263.918H385.32V364.206z M385.32,248.082H263.918V147.794H385.32V248.082z     M385.32,131.959H263.918V15.97c43.327,1.402,85.056,14.299,121.402,37.55V131.959z M401.155,64.623    c24.249,18.508,44.817,41.439,60.422,67.336h-60.422V64.623z M401.155,147.794h69.172c15.944,31.32,24.587,64.994,25.707,100.289    h-94.878V147.794z M401.155,447.355v-67.314h60.427C445.944,406.023,425.375,428.949,401.155,447.355z M470.326,364.206h-69.172    V263.918h94.878C494.913,299.2,486.274,332.868,470.326,364.206z"/>
	  </g>
  </g>
</svg>
```

**Comment by Yomguithereal** [comment]
@gaardhus @asgerkromand I am working on a rewrite currently. I have support for arbitrary svg pictograms with a color over nodes (either the name of the material icon or a custom url). I also have support for arbitrary node shapes using svg (either the name of a predefined builtin shape from material or a custom url). But I don't know how to use your own because I need to either find a way to serve static files through a jupyter magic or to pass the svg string along.

Here is two ugly screenshot so you know what is possible:

![moche](https://user-images.githubusercontent.com/2571951/204902481-bb1a5125-be52-48f2-8ce5-7cf78489e9cf.png)

![shapes](https://user-images.githubusercontent.com/2571951/204902508-06c711fb-f9aa-4d3f-8c72-b15621326d42.png)
