### ISSUE TITLE
There might be an error with start_layout in the newest bump

### ISSUE THREAD

**Issue by asgerkromand** [medialab/ipysigma#180]
I can't get the start_layout attribute of the Sigma instance to work. Ive looked through the sigma.py (https://github.com/medialab/ipysigma/blob/master/ipysigma/sigma.py) and I was wondering whether on line 385 it should be 'start_layout_for_seconds' in the isinstance()-function instead of 'start-layout'?

Example of the code I'm referring to.

```
        if isinstance(start_layout, (int, float)):
            self.start_layout_for_seconds = float(start_layout)
```

**Comment by Yomguithereal** [comment]
`start_layout` has been improved to accept either a bool or a number of seconds to run the initial layout and then stop. But I might have messed up something. Let me check this up.

**Comment by asgerkromand** [comment]
It works perfectly when I assign a float - which is by the way a nice feature (!) - but it doesn't seem to work when I assign a bool.

**Comment by asgerkromand** [comment]
Awesome! Thank u.
