### ISSUE TITLE
Issue with icons when taking a .png-snapshot within ipywidget

### ISSUE THREAD

**Issue by asgerkromand** [medialab/ipysigma#187]
When taking a snapshot in fullscreen-mode, using the bottom-left button 'png' within a ipywidget, the node-icons disappear. 

The png-photo of the network doesn't include the icons neither. 

I'm not sure whether the fullscreen-mode have anything to do with it, but somehow taking a snapshot, alters the icons in the sigma-instance within the ipywidget, and the snapshot-function also alters the icons in the network, that gets printed.

https://user-images.githubusercontent.com/61695016/206201575-7e9e2579-8f47-4c6e-b954-c4f35dc6c591.mp4

**Comment by Yomguithereal** [comment]
@asgerkromand I have fixed the webgl program in charge of this. This fix will be part of next release.

**Comment by asgerkromand** [comment]
Thanks again.
