### ISSUE TITLE
node_shape_mapping is not working for me

### ISSUE THREAD

**Issue by eladaspis** [medialab/ipysigma#211]
I built a graph divided to 2 categories (a,b) and get a basic graph without special shapes.

Here is the code:
![image](https://github.com/medialab/ipysigma/assets/12565881/b3716659-c066-4491-9ff5-52e635b198dc)
How to define the field node_shape_mapping by the expected format?
Is there more comfortable way to define shapes?

Thanks

**Comment by Yomguithereal** [comment]
@eladaspis you are lacking the `node_shape` kwarg for your code to work. You need to give it, for instance, the name of the attribute from which to derive shape like so: `node_shape='category'`. What's more, if you omit `node_shape_mapping`, `ipysigma` will choose the shapes for you.

**Comment by eladaspis** [comment]
I replacing `node_shape_mapping` to `node_shape` and I get the a graph without any shapes

![image](https://github.com/medialab/ipysigma/assets/12565881/a3ac4818-ca79-4831-b15b-cfd5079d1e2b)

**Comment by Yomguithereal** [comment]
It might be linked with #210 I need time to investigate. Can you provide your code in a code fence and not as a screenshot so it can be used to reproduce?

**Comment by eladaspis** [comment]
Yes,
File is attached (inside a zip file)

[ipysigma_shapes.zip](https://github.com/medialab/ipysigma/files/11757462/ipysigma_shapes.zip)

**Comment by Yomguithereal** [comment]
I confirm the issue is the same as #210

**Comment by eladaspis** [comment]
Can you explain me what to do?

In addition I want to enlarge the size of the arrow (with directed graph).

Thanks

**Comment by Yomguithereal** [comment]
> Can you explain me what to do?

There is nothing you can do but wait for me to fix the library then upgrade.

> In addition I want to enlarge the size of the arrow (with directed graph).

Increase the size of the edges. If you want to increase them uncorrelated from the size of the edge this is not supported as of yet.

**Comment by Yomguithereal** [comment]
v0.24.2 is now out. Upgrade and the shape problem should disappear (don't forget to clean browser cache and restart jupyter etc.)
