### ISSUE TITLE
Unable to show sidebar after hiding it.

### ISSUE THREAD

**Issue by sander76** [medialab/ipysigma#213]
The sidebar has a "hide" button, which indeed hides the sidebar. however, there is no way to show the sidebar again. (No "show" button or something).

ipysigma version 0.24.2

btw. Thanks for this awesome notebook !

**Comment by Yomguithereal** [comment]
Hello @sander76. I cannot reproduce on my end. Can you show a screenshot of the issue and tell me which notebook frontend you are using (notebook, lab, vscode, etc.)?

**Comment by sander76** [comment]
Hi @Yomguithereal I am not sure how, but during venv creation my notebook installs version < 7, which indeed has this issue. If I force install version 7 all is good ! 

So the problem is on my side. I'll figure it out. Sorry for this !
