### ISSUE TITLE
enable ipysigma on jupyterlab

### ISSUE THREAD

**Issue by emilienschultz** [medialab/ipysigma#218]
Add in the documentation how to enable the ipysigma widget for jupyter-lab ?
- jupyter labextension enable ipysigma
- jupyter labextension enable ipysigma user
- jupyter labextension enable ipysigma sys-prefix

**Comment by Yomguithereal** [comment]
Normally you shouldn't have to as it is supposed to work out-of-the-box now (right?, riiiiight?) Else I guess you can open a PR on this section: https://github.com/medialab/ipysigma#installation :)

**Comment by emilienschultz** [comment]
Yup I had to do it to enable the widget (jupyterlab 4.0.5). I will try to reproduce the problem and if it persists, I PR

**Comment by Yomguithereal** [comment]
I have it working on 3.6.6. I hope they did not change something again in v4...

**Comment by emilienschultz** [comment]
Seems to be a local problem, I tried with a clean environnement both with 3.6 and 4 and it works well. Sorry for the distrubance ;)

**Comment by Yomguithereal** [comment]
In any case, I don't think this is useless to document this next to the nbextension counterparts.

**Comment by Yomguithereal** [comment]
@emilienschultz I just pushed a slight update to the docs wrt `labextension`. Can you please double check it to make sure I did not mess up the commands (I have never used them, so I am not sure)
