### ISSUE TITLE
edge_type does not work

### ISSUE THREAD

**Issue by PabloVD** [medialab/ipysigma#239]
When writing `edge_type` as argument, it says it does not exist, although according to the README documentation there is an argument like that.

```
Sigma(graph, node_size=graph.degree, node_color='type', edge_color="type", label_density=10, node_border_color_from="node", label_font="cursive", edge_type="type")

TypeError: __init__() got an unexpected keyword argument 'edge_type'
```

**Comment by Yomguithereal** [comment]
@PabloVD the only kwarg related to the edge type currently is `default_edge_type`. I have added some precisions on the README about this. The edge type cannot be mapped to edge attributes or values as of yet. Can I ask you what you are trying to do? Having some edges curved or arrowed and some others not?

**Comment by PabloVD** [comment]
Thanks for answering. I was interested in something similar to that, having different types of lines depending on the edge type, for instance dashed, dotted lines or continuous lines.

**Comment by Yomguithereal** [comment]
I see. Unfortunately sigma does not yet support dashed nor dotted lines as they are quite a challenge to render in webgl. Which means in turn ipysigma does not have a dashed or dotted edge type. Only line, rectangle, arrow, curve.

**Comment by PabloVD** [comment]
Ok, then I'll try to use colors instead of line types for now. Thank you!
